### ISSUE TITLE
"404 page not found" for the UI of solr => [SOLVED]

### ISSUE THREAD

**Issue by steveoriol** [mkalkbrenner/ddev-solr#23]
Solr works very well with Drupal, all index works.
But I don't mange to access UI of solr ... ?
I get this message here : https://<myprject>.ddev.site:8983/
`404 page not found`
do you know why ?
Note:
_I get the same with github.com/ddev/ddev-drupal9-solr_

**Comment by rfay** [comment]
Hi @steveoriol - I imagine you have something else running on port 8983, since you get the same with ddev-drupal9-solr. You can use the debugging techniques in https://ddev.readthedocs.io/en/latest/users/usage/troubleshooting/#web-server-ports-already-occupied to figure out what. 

And of course, do a `ddev poweroff` and use the [other general troubleshooting techniques](https://ddev.readthedocs.io/en/latest/users/usage/troubleshooting/#troubleshooting) to narrow down the problem. And stop your docker provider, etc.

**Comment by steveoriol** [comment]
Hi [**@rfay**](https://github.com/rfay),
Thanks, I finally found the problem. With Firefox, the "**http**://xxxx.ddev.site:8983/" is automatically redirected to "**https**://xxxx.ddev.site:8983/", and it doesn't work...
Using Brave, it works directly! 
Thanks again ;-)
